# permissions for end users to view centralprobes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: centralprobe-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-stack
    app.kubernetes.io/part-of: kube-stack
    app.kubernetes.io/managed-by: kustomize
  name: centralprobe-viewer-role
rules:
- apiGroups:
  - centralprobe.kube-stack.me
  resources:
  - centralprobes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - centralprobe.kube-stack.me
  resources:
  - centralprobes/status
  verbs:
  - get
