---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers/finalizers
  verbs:
  - update
- apiGroups:
  - podmarker.kube-stack.me
  resources:
  - podmarkers/status
  verbs:
  - get
  - patch
  - update
